### ISSUE TITLE
Loads the most recent history entry not the current

### ISSUE THREAD

**Issue by davidpierson** [shkdee/KeePassPHP#2]
Hi,
Thank you for a brilliant piece of work! I do a little PHP and I had no idea that PHP projects could be written so well. I do appreciate the structure and the commenting. This is elegant code, for sure. I will deploy it on a domain soon. Testing in my local now. 

I am using your UI (again, thanks) and I find that it actually displays the most recent history entry instead of the current entry. I have not attempted to dig through the code to find out why. However, I was looking at an exported XML. Perhaps it is processing the history entries, which come after the current entry? This would fit the behaviour. 

Best regards
David Pierson

**Comment by shkdee** [comment]
Hi, thanks for the feedback!

Yeah, so as the main user of this thing (I assume, but I am glad to know that someone else uses it too!), I already noticed this problem. It happens exactly as you assume, I only process the very first entry of history, which may not be the most recent.

Unfortunately, as you may have noticed as well, I have not been working on this project for a long time, but I will try to solve at least that (and a few other design issues I have in mind) as soon as possible.

**Comment by davidpierson** [comment]
Hi, you're welcome!

After looking through the import, I wonder if xmlstackreader is recursing into the history xml. Once it is in the history XML entries, it is replacing the current entries of the name id, with the entries from history. The last history item is the one that remains when finished. 
This just a guess from the overall structure of the xml reader. I have not fully understood all the workings yet. 
Best regards
David

**Comment by cisso** [comment]
Just a quick guess (without having used KeePassPHP yet): Could be that the retrieved key value is constant, and as such earlier array entries get overwritten?

**Comment by shkdee** [comment]
I feel slightly ashamed, but the issue was more stupid (and actually harder to find): a forgot to strtolower the "History" tag :-(
