### ISSUE TITLE
Deprecated Function... OpenSSL

### ISSUE THREAD

**Issue by lmsvr** [shkdee/KeePassPHP#6]
I've been testing your project but unfortunately I haven't had any success in getting it up and running... 
I'm using MacOS High Sierra with PHP 7.1 and mcrypts extension installed via home-brew. If I read your README file correctly the mcrypts extension is known to be less reliable and OpenSSL is more stable.  I do have OpenSSL installed but is your code utilizing the extension?  It appears to me that it's not.  Whatever the case, hopefully you have an obvious tip or two that I've overlooked.  

Thanks

Deprecated: Function mcrypt_generic() is deprecated in /Volumes/Sites/KeePassPHP-1.1.0-RC/keepassphp/util/cipher.php on line 284
PHP Deprecated:  Function mcrypt_generic() is deprecated in /Volumes/Sites/KeePassPHP-1.1.0-RC/keepassphp/util/cipher.php on line 284
Deprecated: Function mcrypt_generic_deinit() is deprecated in /Volumes/Sites/KeePassPHP-1.1.0-RC/keepassphp/util/cipher.php on line 349
PHP Deprecated:  Function mcrypt_module_close() is deprecated in /Volumes/Sites/KeePassPHP-1.1.0-RC/keepassphp/util/cipher.php on line 350

**Comment by shkdee** [comment]
KeePassPHP does use the OpenSSL extension if it can check that it is loaded (see [this method](https://github.com/shkdee/KeePassPHP/blob/286553ee82d91fb4b41ffd3b0160b5920ba22d64/keepassphp/util/cipher.php#L120)). But here, indeed, if mcrypt functions are called, it means that OpenSSL is not detected for some reason. I am not a big specialist of PHP extensions, but are your sure that your PHP has the openssl extension loaded ? Does it show on a phpinfo page for example, or does `extension_loaded("openssl")` return true ?  Maybe having OpenSSL installed on the system is not enough ; PHP must be aware of it somehow.

**Comment by shkdee** [comment]
FWIW, I know it's been a long time, but I accidentally found the cause for your issue, when switching to PHP 7.2 which does not have mcrypt. It turns out that I did the huge mistake or thinking that PHP was like any other language, and that openssl was indeed not used. The commit 
ff9a00a  fixes that.
